name: Build TDLib for Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [armeabi-v7a]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          clang \
          cmake \
          git \
          libssl-dev \
          pkg-config \
          zlib1g-dev \
          unzip \
          wget

    - name: Download and set up Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip
        echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r21e" >> $GITHUB_ENV

    - name: Download and set up OpenSSL
      run: |
        wget https://www.openssl.org/source/openssl-3.3.0.tar.gz
        tar -xzf openssl-3.3.0.tar.gz
        cd openssl-3.3.0
        ./config
        make
        sudo make install
        echo "OPENSSL_ROOT_DIR=/usr/local/ssl" >> $GITHUB_ENV
        echo "OPENSSL_LIBRARIES=/usr/local/ssl/lib" >> $GITHUB_ENV

    - name: Generate necessary files
      run: |
        mkdir -p tdutils/generate/auto
        touch tdutils/generate/auto/mime_type_to_extension.cpp

    - name: Configure and build TDLib
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=${{ matrix.arch }} -DANDROID_NATIVE_API_LEVEL=21 ..
        cmake --build . --config Release

    - name: Upload .so files
      uses: actions/upload-artifact@v2
      with:
        name: tdlib-android-${{ matrix.arch }}
        path: build/libtdjson.so
