name: Build TDLib for Android

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          clang \
          cmake \
          git \
          libssl-dev \
          pkg-config \
          zlib1g-dev \
          unzip \
          wget \
          php \
          perl \
          gperf

    - name: Check environment
      run: |
        cd td/examples/android
        ./check-environment.sh

    - name: Fetch Android SDK
      run: |
        cd td/examples/android
        ./fetch-sdk.sh

    - name: Build OpenSSL
      run: |
        cd td/examples/android
        ./build-openssl.sh

    - name: Build TDLib
      run: |
        cd td/examples/android
        ./build-tdlib.sh

    - name: Upload .so files
      uses: actions/upload-artifact@v2
      with:
        name: tdlib-android-libs
        path: tdlib/libs/**/*.so
